#!/usr/bin/env bash
# Native (non-Docker) setup for Hermes Agent + optional AIRI bridge.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export HERMES_HOME="$ROOT/data/hermes"
export PATH="${HOME}/.local/bin:${PATH}"

echo "==> Ensuring git submodules are initialized..."
git submodule update --init --recursive

if [ ! -f .env ]; then
  echo "==> Creating .env from .env.example..."
  cp .env.example .env
  if command -v openssl >/dev/null 2>&1; then
    key="$(openssl rand -hex 32)"
    sed "s/^API_SERVER_KEY=$/API_SERVER_KEY=${key}/" .env > .env.tmp && mv .env.tmp .env
    echo "    Generated a random API_SERVER_KEY."
  fi
  {
    echo "HERMES_UID=$(id -u)"
    echo "HERMES_GID=$(id -g)"
  } >> .env
fi

mkdir -p "$HERMES_HOME"

# shellcheck disable=SC1091
source "$ROOT/scripts/lib/hermes-env.sh"

if [ ! -x "$VENV_PYTHON" ]; then
  echo "==> Installing uv (if needed) and Hermes virtualenv..."
  if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="${HOME}/.local/bin:${PATH}"
  fi
  uv venv "$ROOT/.venv" --python 3.11
  uv pip install --python "$VENV_PYTHON" -e "$ROOT/vendor/hermes-agent[all]"
fi

echo "==> Writing Hermes API server config..."
API_KEY="$(grep '^API_SERVER_KEY=' .env | cut -d= -f2-)"
CORS="$(grep '^API_SERVER_CORS_ORIGINS=' .env | cut -d= -f2- || true)"
CORS="${CORS:-http://localhost:6620,http://127.0.0.1:6620}"
MODEL_NAME="$(grep '^API_SERVER_MODEL_NAME=' .env | cut -d= -f2- || true)"
MODEL_NAME="${MODEL_NAME:-hermes-agent}"

cat > "$HERMES_HOME/.env" <<EOF
# Generated by scripts/setup-native.sh — Hermes reads this from HERMES_HOME.
API_SERVER_ENABLED=true
API_SERVER_HOST=127.0.0.1
API_SERVER_PORT=8642
API_SERVER_KEY=${API_KEY}
API_SERVER_CORS_ORIGINS=${CORS}
API_SERVER_MODEL_NAME=${MODEL_NAME}
EOF

cat <<EOF

Native setup complete.

Next: connect your Nous subscription (pick one):

  A) OAuth (recommended — covers models + Tool Gateway):
       source scripts/activate-hermes.sh
       hermes setup --portal

     Headless / SSH? Use device approval instead:
       hermes auth add nous --no-browser

  B) API key from portal.nousresearch.com → API keys:
       source scripts/activate-hermes.sh
       hermes auth add nous --type api-key

Then start the agent gateway (cron + webhooks + API server):
       ./scripts/start-hermes.sh

Verify:
       hermes portal info
       curl -fsS http://127.0.0.1:8642/health

AIRI (optional, needs Docker): docker compose up -d --build
EOF
